<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>Mas de callbacks</title>
</head>
<body>
	<h1 id="agenda">Estoy despertando...</h1>

	<script type="text/javascript">
		const DESPERTAR = 3000
		const DUCHA = 2000
		const VESTIRSE = 2000
		const DESAYUNAR = 3000
		const PLATZI = 5000
		const $agenda = document.getElementById("agenda")

		// const despertar = new Promise ((resolve, reject) => {
		// 	setTimeout(() => resolve('Ahora me estoy duchando...'), DESPERTAR)
		// })
		// despertar
		// .then((msg) => console.log(msg))
		// .catch((msg) => console.log(msg))
		function despertar () {
			return new Promise((resolve, reject) => {
				setTimeout(() => resolve('Ahora me estoy duchando...'), DESPERTAR)
			})
		}
		function ducha(msg) {
			$agenda.textContent = msg
			return new Promise((resolve, reject) => {
				setTimeout(() => resolve("Ahora me estoy vistiendo..."), DUCHA)
			})
		}

		function vestirme(msg) {
			$agenda.textContent = msg
			return new Promise((resolve, reject) => {
				setTimeout(() => resolve("Ahora estoy desayunado..."), VESTIRSE)
			})
		}
		function desayunar(msg) {
			$agenda.textContent = msg
			return new Promise((resolve, reject) => {
				// setTimeout(() => resolve("Ahora estoy aprendiendo en platzi..."), DESAYUNAR)
				setTimeout(() => reject(new Error("NO HAY COMIDA!")))
			})
		}
		function platzi(msg) {
			$agenda.textContent = msg
			return new Promise((resolve, reject) => {
				setTimeout(() => resolve("Ah que gran dia!"), PLATZI)
			})
		}
		function final(msg) {
			$agenda.textContent = msg
		}
		function error(err) {
			console.log(`Algún error ocurrió: ${err}`)
		}
		despertar()
		.then(ducha)
		.then(vestirme)
		.then(desayunar)
		.then(platzi)
		.then(final)
		.catch(error)

	</script>
</body>
</html>